name: regen
description: Gamified Recycling System for USM
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management and Utilities
  provider: ^6.1.1 
  intl: ^0.19.0
  url_launcher: ^6.2.2
  percent_indicator: ^4.2.3

  # Firebase Dependencies (Consolidated and checked for duplicates)
  firebase_core: ^2.27.0
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.11
  google_sign_in: ^6.2.2

  # Feature Dependencies (from original list)
  image_picker: ^1.0.4
  #qr_code_scanner: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
  - assets/images/

